##====================================================================================================
## Supplementary Figure S16: Environmental Predictor Multicollinearity Analysis
##
## This figure displays the correlation matrix and multicollinearity analysis of environmental 
## predictors used in species distribution modeling. The analysis identifies highly correlated 
## environmental variables to inform predictor selection and avoid redundancy in modeling workflows.
##
## Author:      Dominic Eriksson
##              Environmental Physics Group, UP
##              ETH Zürich, Switzerland
## Contact:     deriksson@ethz.ch
## Date:        February 27th, 2026
## Affiliation: ETH Zürich, Environmental Physics Group, UP
##
## NOTE: Figure S16 is a CEPHALOPOD model output created automatically and can be accessed 
##       in the MODEL output file "02_env_cor.pdf"
##
## Required R packages:
## - Generated automatically by CEPHALOPOD framework
##====================================================================================================

# NOTE: This figure is automatically generated by the CEPHALOPOD modeling framework
# and does not require manual R script execution. The environmental predictor 
# multicollinearity analysis can be found in the model output file "02_env_cor.pdf"

cat("Figure S16 is automatically generated by CEPHALOPOD.\n")
cat("Please refer to model output file: 02_env_cor.pdf\n")

### ====================================================================================================================
### END OF SCRIPT
### ====================================================================================================================
